on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v4
    
    - name: 📂 Sync Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        target-server: ftpupload.net
        remote-user: if0_37944711
        private-ssh-key: ${{ secrets.ftp_password }}
        local-dir: ./
        server-dir: /htdocs/
